# Generated by Django 5.2.4 on 2025-08-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="products/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount_percent", models.PositiveIntegerField(default=0)),
                ("rating", models.FloatField(default=0)),
                ("num_ratings", models.PositiveIntegerField(default=0)),
                ("quantity_available", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
