# Generated by Django 5.2 on 2025-10-08 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_create_order_models"),
        ("store", "0002_order_orderitem"),
    ]

    operations = []
