# Generated by Django 5.2 on 2025-10-09 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_merge_0002_create_order_models_0002_order_orderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("XS", "Extra Small"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                            ("XL", "Extra Large"),
                            ("XXL", "Double Extra Large"),
                            ("100g", "100 Grams"),
                            ("250g", "250 Grams"),
                            ("500g", "500 Grams"),
                            ("1kg", "1 Kilogram"),
                            ("5kg", "5 Kilograms"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity_available",
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about this order", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cod", "Cash on Delivery"),
                    ("online", "Online Payment"),
                    ("upi", "UPI Transfer"),
                ],
                default="cod",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.BooleanField(default=False, verbose_name="Payment Received"),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Feature this product on homepage"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.TextField(
                blank=True, help_text="Brief product description for listings"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="URL-friendly name for product",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="special_features",
            field=models.CharField(
                blank=True,
                choices=[
                    ("organic", "Organic"),
                    ("pure_a2", "Pure A2"),
                    ("no_preservatives", "No Preservatives"),
                    ("handmade", "Handmade"),
                    ("gluten_free", "Gluten Free"),
                    ("farm_fresh", "Farm Fresh"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of items in stock"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In Stock"),
                    ("low_stock", "Low Stock"),
                    ("out_of_stock", "Out of Stock"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.category"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="store.productsize"
            ),
        ),
    ]
