# Generated by Django 5.2 on 2025-10-09 17:30

from django.db import migrations


def populate_product_stock(apps, schema_editor):
    Product = apps.get_model('store', 'Product')
    ProductSize = apps.get_model('store', 'ProductSize')
    ProductStock = apps.get_model('store', 'ProductStock')
    
    for product in Product.objects.all():
        for size in product.sizes.all():
            ProductStock.objects.get_or_create(
                product=product,
                size=size,
                defaults={'quantity': 5}
            )


def reverse_populate_product_stock(apps, schema_editor):
    ProductStock = apps.get_model('store', 'ProductStock')
    ProductStock.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_options_productstock"),
    ]

    operations = [
        migrations.RunPython(populate_product_stock, reverse_populate_product_stock),
    ]
