# Generated by Django 5.2 on 2025-10-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_coupon_alter_product_options_order_coupon_discount_and_more"),
    ]

    operations = []
