# Generated by Django 5.2 on 2025-10-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_auto_20251009_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstock",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Price for this size",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="name",
            field=models.CharField(
                choices=[
                    ("XS", "Extra Small"),
                    ("S", "Small"),
                    ("M", "Medium"),
                    ("L", "Large"),
                    ("XL", "Extra Large"),
                    ("XXL", "Double Extra Large"),
                    ("100g", "100 Grams"),
                    ("250g", "250 Grams"),
                    ("500g", "500 Grams"),
                    ("900g", "900 Grams"),
                    ("1kg", "1 Kilogram"),
                    ("5kg", "5 Kilograms"),
                ],
                max_length=10,
            ),
        ),
    ]
